repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: debug-statements

    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
            language_version: python3
            args: [--line-length=88]

    - repo: https://github.com/pycqa/flake8
      rev: 7.1.1
      hooks:
          - id: flake8
            additional_dependencies: [flake8-docstrings]

    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0
      hooks:
          - id: pydocstyle
            args: [--config=pydocstyle.ini]

    # Temporariamente desabilitado devido a problemas de configuração
    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: v1.13.0
    #   hooks:
    #       - id: mypy
    #         additional_dependencies: [django-stubs, types-requests]
    #         args: [--config-file=mypy.ini]
    #         files: ^project/core/
    #         env:
    #           PYTHONPATH: project

    - repo: local
      hooks:
          - id: pytest-check
            name: pytest-check
            entry: bash -c 'cd project && python -m pytest --tb=short -q'
            language: system
            pass_filenames: false
            always_run: false
            stages: [manual]
